#service 
apiVersion: v1
kind: Service
metadata:
  name: jupyter-port
spec:
  type: LoadBalancer
  ports:
    - port: 6006
      targetPort: 6006
  selector:
    app: docker-image 

---

apiVersion: v1
kind: Service
metadata:
  name: http-port
spec:
  type: ClusterIP
  ports:
    - port: 88
      targetPort: 8888
  selector:
    app: docker-image 